### ISSUE TITLE
Hi, when I train the model, I get a error but I can't solve it.

### ISSUE THREAD

**Issue by blazexpire** [ItamarDavid/Subsampled-Brain-MRI-Reconstruction-by-Generative-Adversarial-Neural-Networks#20]
I have this error information, and I tried lots of ways to fix it, but they don't work.
 File "train.py", line 253, in <module>
    train(args)
  File "train.py", line 100, in train
    rec_img, rec_Kspace, rec_mid_image = G_model(masked_Kspaces)
File "/home/lzx/gyc/anaconda3/envs/subgan/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (CUDAComplexFloatType) and weight type (torch.cuda.FloatTensor) should be the same

**Comment by ElisabettaSpinazzola** [comment]
Hi, how do you solved, this issue?
